### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by veredrec** [facn2/path-18-app#2]
#1 
As a young person I want the sign up process to be simple with a minimal amount of input in order to use the app

### Acceptance criteria

- [x] sign up form with fields for personal details and grades #16 
- [x] adding the form data to the database #16
- [ ] front end and back end validation #18 
- [x] implement OAuth #17 #19 
- [x] style component #20
