### ISSUE TITLE
Change text to Arabic

### ISSUE THREAD

**Issue by matthewdking** [facn2/path-18-app#79]
In the future it would be good to offer full language support for both Arabic and Hebrew. For now we should concentrate on changing the language to Arabic ready for user testing.

**Comment by Karyum** [comment]
alright so not sure whats the best approach for translation (both Arabic and Hebrew), and the way im going to probably do this will make the front-end code a lil bit sensitive (_which is not great for future development if there is any_). what needs to be done for this : 
- [x] Add a way to change between Hebrew and Arabic in the navbar, which would change the redux state to that language. #110 
- [x] use that state to render different language, for everywhere a career detail or name appears. #112 
- [x] Create a Json file that contains Arabic and Hebrew translations for the rest of the app. #108 
- [x] manipulate the database so we would change the names of the universities  to Arabic and Hebrew versions . _this is a bit tricky_
- [x] fix bugs :smile:

**Comment by Karyum** [comment]
but before starting with this i will look further more if there's a different approach for this, maybe use like react-intl and i18n
